#include <metal_stdlib>
#include "ShaderWallpaper.h"
using namespace metal;



// Fallback for app builds that validate ShaderWallpaper.h includes but do not
// inject the public header source into runtime Metal compilation.
#ifndef SHADER_WALLPAPER_H
#define SHADER_WALLPAPER_H
struct ShaderWallpaperUniforms {
    float time;
    float2 resolution;
    float4 mouse;
};

struct ShaderWallpaperVertexOut {
    float4 position [[position]];
    float2 texCoord;
};
#endif

static float sdCircle(float2 p, float radius) {
    return length(p) - radius;
}

static float segmentDistance(float2 p, float2 a, float2 b) {
    float2 pa = p - a;
    float2 ba = b - a;
    float h = clamp(dot(pa, ba) / dot(ba, ba), 0.0, 1.0);
    return length(pa - ba * h);
}

static float drawSegment(float2 p, float2 a, float2 b, float width) {
    return 1.0 - smoothstep(width * 0.45, width, segmentDistance(p, a, b));
}

static float drawRing(float2 p, float2 center, float radius, float width) {
    return 1.0 - smoothstep(0.0, width, abs(length(p - center) - radius));
}


// Original Font Data: 
//
// http://www.fial.com/~scott/tamsyn-font/ 
//
// Range 0x20 to 0x7f (inclusive)
//
// Each glyph is 8x16 pixels. The table stores 96 glyphs, one per ASCII code
// from 0x20 through 0x7F.
//
// Each glyph is packed into a uint4, with 4 rows per uint:
//   glyph[0] = rows 0..3, glyph[1] = rows 4..7, glyph[2] = rows 8..11,
//   glyph[3] = rows 12..15
//
// Within each row byte, bit 7 is the leftmost pixel and bit 0 is the rightmost.
// This means x=0 samples the MSB and x=7 samples the LSB.
//
// The table is stored in the Metal `constant` address space for program-scope data.
// Generated by bdf_to_metalh.py on 2026-06-08T20:27:11.440585Z
// Input BDF -> font table for range 0x20..0x7F, 8x16 glyphs


constant uint4 font_data[96] = {
    { 0x00000000, 0x00000000, 0x00000000, 0x00000000 },      // 0x20                       
    { 0x00000000, 0x00001818, 0x3C3C1818, 0x0000183C },      // 0x21 !                     
    { 0x00000000, 0x00000000, 0x6C000000, 0x006C6C6C },      // 0x22 "                     
    { 0x00000000, 0x367F3636, 0x367F3636, 0x00000036 },      // 0x23 #                     
    { 0x18000000, 0x06067C18, 0x3E60603C, 0x00001818 },      // 0x24 $                     
    { 0x00000000, 0x1E3B5B0E, 0x6D6E3C08, 0x00000038 },      // 0x25 %                     
    { 0x00000000, 0x6D66663B, 0x6C6C3839, 0x0000386C },      // 0x26 &                     
    { 0x00000000, 0x00000000, 0x18000000, 0x00181818 },      // 0x27 '                     
    { 0x180C0000, 0x30303018, 0x18303030, 0x00000C18 },      // 0x28 (                     
    { 0x18300000, 0x0C0C0C18, 0x180C0C0C, 0x00003018 },      // 0x29 )                     
    { 0x00000000, 0x1C360000, 0x00361C7F, 0x00000000 },      // 0x2A *                     
    { 0x00000000, 0x18181800, 0x181818FF, 0x00000000 },      // 0x2B +                     
    { 0x0C0C1800, 0x00001C1C, 0x00000000, 0x00000000 },      // 0x2C ,                     
    { 0x00000000, 0x00000000, 0x0000007E, 0x00000000 },      // 0x2D -                     
    { 0x00000000, 0x00001C1C, 0x00000000, 0x00000000 },      // 0x2E .                     
    { 0x60600000, 0x18183030, 0x06060C0C, 0x00000303 },      // 0x2F /                     
    { 0x00000000, 0x7676663C, 0x666E6E66, 0x0000003C },      // 0x30 0                     
    { 0x00000000, 0x1818187E, 0x38781818, 0x00000018 },      // 0x31 1                     
    { 0x00000000, 0x1830607E, 0x6606060C, 0x0000003C },      // 0x32 2                     
    { 0x00000000, 0x0606663C, 0x060C1C06, 0x0000007E },      // 0x33 3                     
    { 0x00000000, 0x7F060606, 0x0E1E3666, 0x00000006 },      // 0x34 4                     
    { 0x00000000, 0x0606663C, 0x60607C06, 0x0000007E },      // 0x35 5                     
    { 0x00000000, 0x6666663C, 0x30607C66, 0x00000018 },      // 0x36 6                     
    { 0x00000000, 0x18303030, 0x060C0C18, 0x0000007E },      // 0x37 7                     
    { 0x00000000, 0x6666663C, 0x6666663C, 0x0000003C },      // 0x38 8                     
    { 0x00000000, 0x3E060C18, 0x66666666, 0x0000003C },      // 0x39 9                     
    { 0x00000000, 0x00001C1C, 0x001C1C00, 0x00000000 },      // 0x3A :                     
    { 0x0C0C1800, 0x00001C1C, 0x001C1C00, 0x00000000 },      // 0x3B ;                     
    { 0x00000000, 0x30180C06, 0x0C183060, 0x00000006 },      // 0x3C <                     
    { 0x00000000, 0x007E0000, 0x00007E00, 0x00000000 },      // 0x3D =                     
    { 0x00000000, 0x0C183060, 0x30180C06, 0x00000060 },      // 0x3E >                     
    { 0x00000000, 0x00001818, 0x06060C18, 0x00003C46 },      // 0x3F ?                     
    { 0x603F0000, 0x6B6F6F60, 0x636F6B6B, 0x00003E63 },      // 0x40 @                     
    { 0x00000000, 0x7E666666, 0x3C666666, 0x00000018 },      // 0x41 A                     
    { 0x00000000, 0x6666667C, 0x6666667C, 0x0000007C },      // 0x42 B                     
    { 0x00000000, 0x6060301E, 0x30606060, 0x0000001E },      // 0x43 C                     
    { 0x00000000, 0x66666C78, 0x6C666666, 0x00000078 },      // 0x44 D                     
    { 0x00000000, 0x6060607E, 0x6060607C, 0x0000007E },      // 0x45 E                     
    { 0x00000000, 0x60606060, 0x6060607C, 0x0000007E },      // 0x46 F                     
    { 0x00000000, 0x6666361E, 0x30606060, 0x0000001E },      // 0x47 G                     
    { 0x00000000, 0x66666666, 0x6666667E, 0x00000066 },      // 0x48 H                     
    { 0x00000000, 0x1818187E, 0x18181818, 0x0000007E },      // 0x49 I                     
    { 0x00000000, 0x0666663C, 0x06060606, 0x00000006 },      // 0x4A J                     
    { 0x00000000, 0x786C6663, 0x666C7870, 0x00000063 },      // 0x4B K                     
    { 0x00000000, 0x6060607E, 0x60606060, 0x00000060 },      // 0x4C L                     
    { 0x00000000, 0x63636363, 0x777F6B63, 0x00000063 },      // 0x4D M                     
    { 0x00000000, 0x63636363, 0x737B6F67, 0x00000063 },      // 0x4E N                     
    { 0x00000000, 0x6666663C, 0x66666666, 0x0000003C },      // 0x4F O                     
    { 0x00000000, 0x60606060, 0x6666667C, 0x0000007C },      // 0x50 P                     
    { 0x0F000000, 0x6666663C, 0x66666666, 0x0000003C },      // 0x51 Q                     
    { 0x00000000, 0x6C666666, 0x6666667C, 0x0000007C },      // 0x52 R                     
    { 0x00000000, 0x0E06067C, 0x6060703C, 0x0000003E },      // 0x53 S                     
    { 0x00000000, 0x18181818, 0x18181818, 0x000000FF },      // 0x54 T                     
    { 0x00000000, 0x6666663C, 0x66666666, 0x00000066 },      // 0x55 U                     
    { 0x00000000, 0x66663C18, 0x66666666, 0x00000066 },      // 0x56 V                     
    { 0x00000000, 0x6B7F7763, 0x63636363, 0x00000063 },      // 0x57 W                     
    { 0x00000000, 0x3C666666, 0x66663C18, 0x00000066 },      // 0x58 X                     
    { 0x00000000, 0x18181818, 0x66663C18, 0x00000066 },      // 0x59 Y                     
    { 0x00000000, 0x3030607E, 0x0C0C1818, 0x0000007E },      // 0x5A Z                     
    { 0x303E0000, 0x30303030, 0x30303030, 0x00003E30 },      // 0x5B [                     
    { 0x03030000, 0x0C0C0606, 0x30301818, 0x00006060 },      // 0x5C \                     
    { 0x0C7C0000, 0x0C0C0C0C, 0x0C0C0C0C, 0x00007C0C },      // 0x5D ]                     
    { 0x00000000, 0x00000000, 0x66000000, 0x0000183C },      // 0x5E ^                     
    { 0x00FF0000, 0x00000000, 0x00000000, 0x00000000 },      // 0x5F _                     
    { 0x00000000, 0x00000000, 0x06000000, 0x0030180C },      // 0x60 `                     
    { 0x00000000, 0x3E66663E, 0x003C0606, 0x00000000 },      // 0x61 a                     
    { 0x00000000, 0x6666667C, 0x607C6666, 0x00006060 },      // 0x62 b                     
    { 0x00000000, 0x6060603E, 0x003E6060, 0x00000000 },      // 0x63 c                     
    { 0x00000000, 0x6666663E, 0x063E6666, 0x00000606 },      // 0x64 d                     
    { 0x00000000, 0x7E60603E, 0x003C6666, 0x00000000 },      // 0x65 e                     
    { 0x00000000, 0x30303030, 0x307E3030, 0x00001E30 },      // 0x66 f                     
    { 0x63633E00, 0x663C603E, 0x003F6666, 0x00000000 },      // 0x67 g                     
    { 0x00000000, 0x66666666, 0x607C6666, 0x00006060 },      // 0x68 h                     
    { 0x00000000, 0x1818187E, 0x00781818, 0x00001818 },      // 0x69 i                     
    { 0x0C0C7800, 0x0C0C0C0C, 0x003C0C0C, 0x00000C0C },      // 0x6A j                     
    { 0x00000000, 0x786C6663, 0x60666C78, 0x00006060 },      // 0x6B k                     
    { 0x00000000, 0x1818180E, 0x18181818, 0x00007818 },      // 0x6C l                     
    { 0x00000000, 0x6B6B6B6B, 0x007E6B6B, 0x00000000 },      // 0x6D m                     
    { 0x00000000, 0x66666666, 0x007C6666, 0x00000000 },      // 0x6E n                     
    { 0x00000000, 0x6666663C, 0x003C6666, 0x00000000 },      // 0x6F o                     
    { 0x60606000, 0x6666667C, 0x007C6666, 0x00000000 },      // 0x70 p                     
    { 0x06060600, 0x6666663E, 0x003E6666, 0x00000000 },      // 0x71 q                     
    { 0x00000000, 0x60606060, 0x006E7060, 0x00000000 },      // 0x72 r                     
    { 0x00000000, 0x3C0E067C, 0x003E6070, 0x00000000 },      // 0x73 s                     
    { 0x00000000, 0x3030301E, 0x307E3030, 0x00000030 },      // 0x74 t                     
    { 0x00000000, 0x6666663E, 0x00666666, 0x00000000 },      // 0x75 u                     
    { 0x00000000, 0x66663C18, 0x00666666, 0x00000000 },      // 0x76 v                     
    { 0x00000000, 0x6B6B6B7E, 0x006B6B6B, 0x00000000 },      // 0x77 w                     
    { 0x00000000, 0x183C6666, 0x0066663C, 0x00000000 },      // 0x78 x                     
    { 0x06063C00, 0x6666663E, 0x00666666, 0x00000000 },      // 0x79 y                     
    { 0x00000000, 0x1830607E, 0x007E060C, 0x00000000 },      // 0x7A z                     
    { 0x180E0000, 0x18181818, 0x181818F0, 0x000E1818 },      // 0x7B {                     
    { 0x18180000, 0x18181818, 0x18181818, 0x00181818 },      // 0x7C |                     
    { 0x18700000, 0x18181818, 0x1818180F, 0x00701818 },      // 0x7D }                     
    { 0x00000000, 0x00000000, 0x6F660000, 0x0000337B },      // 0x7E ~                     
    { 0x00000000, 0x00000000, 0x00000000, 0x00000000 },      // 0x7F                       
};

static uint getFontRow(uint index, uint row) {
    // Each glyph is 16 rows tall, with 8 bits per row.
    // The font_data stores 4 rows in each uint, packed as 8-bit bytes.
    // For a given row:
    //   row >> 2 selects the containing uint within the glyph.
    //   row & 3 selects which of the 4 bytes inside that uint to use.
    // The selected byte is then shifted down and masked to yield one row.
    uint4 glyph = font_data[index];
    uint word = glyph[row >> 2];
    uint shift = (row & 3u) * 8u;
    return (word >> shift) & 0xFFu;
}

static float drawText(float2 p) {
    const char text[] = "WHAT IS GOING ON";
    const uint textLength = 17u;
    const uint glyphWidth = 8u;
    const uint cellWidth = 9u;
    const uint textHeight = 16u;
    const float pixelSize = 0.015;
    const float totalWidth = float(cellWidth) * float(textLength) * pixelSize - pixelSize;
    const float totalHeight = float(textHeight) * pixelSize;
    // Place the top-left of the text block at y=0.12.
    // `uv.y` is computed so that positive `iy` goes downward, matching the
    // glyph row ordering in the font table.
    float2 origin = float2(-totalWidth * 0.5, 0.12);
    float2 uv = float2((p.x - origin.x) / pixelSize, (origin.y - p.y) / pixelSize);

    int ix = int(floor(uv.x));
    int iy = int(floor(uv.y));
    if (ix < 0 || iy < 0) return 0.0;
    if (iy >= int(textHeight)) return 0.0;

    uint charIndex = uint(ix) / cellWidth;
    if (charIndex >= textLength) return 0.0;

    uint xInChar = uint(ix) % cellWidth;
    if (xInChar >= glyphWidth) return 0.0;

    uint c = uint(text[charIndex]);
    if (c < 0x20u || c > 0x7Fu) return 0.0;

    // Map the current pixel row into the glyph bitmap.
    // `iy` is the vertical row within the glyph, with 0 at the top.
    uint row = getFontRow(c - 0x20u, uint(iy));

    // Each row is stored as an 8-bit byte where bit 7 is the leftmost pixel.
    // `xInChar` is the horizontal pixel coordinate inside the glyph, so we
    // sample the MSB-first byte by shifting by (7 - xInChar).
    uint bit = (row >> (7u - xInChar)) & 1u;
    if (bit == 0u) return 0.0;

    float2 fracPos = fract(uv);
    float alpha = 1.0 - smoothstep(0.45, 0.5, max(abs(fracPos.x - 0.5), abs(fracPos.y - 0.5)));
    return alpha;
}

fragment float4 helloWorldShader(
    ShaderWallpaperVertexOut in [[stage_in]],
    constant ShaderWallpaperUniforms& u [[buffer(0)]]
) {
    float2 uv = in.texCoord;
    float2 p = (uv - 0.5) * float2(u.resolution.x / max(u.resolution.y, 1.0), 1.0) * 2.0;

    float t = u.time;


    float waves = sin((p.x + p.y) * 20.0 + t * 1.4) * 0.5 + 0.5;
    float3 skyA = float3(0.02, 0.03, 0.12);
    float3 skyB = float3(0.10, 0.00, 0.22);
    float3 color = mix(skyA, skyB, uv.y + 0.18 * waves);


    // Floating confetti bubbles.
    for (int i = 0; i < 18; i++) {
        float fi = float(i);
        float2 c = fract(float2(fi * 0.137, fi * 0.271) + float2(0.03 * sin(t * 0.23 + fi), -t * (0.018 + fi * 0.0009)));
        float radius = 0.012 + 0.018 * fract(fi * 0.37);
        float bubble = 1.0 - smoothstep(0.0, radius, distance(uv, c));
        float3 bubbleColor = 0.55 + 0.45 * cos(float3(0.0, 2.1, 4.2) + t + fi);
        color += bubble * bubbleColor * 0.35;
    }

    float glow = drawText(p + float2(0.02 * sin(t * 4.0), 0.1 * sin(t * 2.0)) * 0.98);
    float3 rainbow = 0.55 + 0.45 * cos(float3(0.0, 2.0, 4.0) + p.x * 4.0 + t * 2.0);
    color += rainbow * glow * 0.8;
   
    // Soft vignette keeps desktop edges calm.
    float vignette = smoothstep(1.25, 0.25, length(uv - 0.5));
    color *= 0.3 + 0.35 * vignette;

    return float4(color, 1.0);
}
